# Generated by Django 5.0.6 on 2024-06-11 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100, unique=True, verbose_name='Název kategorie')),
                ('popis', models.TextField(blank=True, null=True, verbose_name='Popis kategorie')),
            ],
            options={
                'verbose_name': 'Kategorie',
                'verbose_name_plural': 'Kategorie',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200, verbose_name='Název projektu')),
                ('popis', models.TextField(blank=True, null=True, verbose_name='Popis projektu')),
                ('start_date', models.DateField(verbose_name='Datum zahájení')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Datum ukončení')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekty',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200, verbose_name='Název úkolu')),
                ('popis', models.TextField(blank=True, null=True, verbose_name='Popis úkolu')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Termín splnění')),
                ('priority', models.CharField(choices=[('low', 'Nízká'), ('medium', 'Střední'), ('high', 'Vysoká')], default='medium', max_length=6, verbose_name='Priorita')),
                ('status', models.CharField(choices=[('pending', 'Čekající'), ('in_progress', 'V proběhu'), ('completed', 'Dokončeno')], default='pending', max_length=12, verbose_name='Stav')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='ukoly.category', verbose_name='Kategorie')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ukoly.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Úkol',
                'verbose_name_plural': 'Úkoly',
                'ordering': ['due_date', 'priority'],
            },
        ),
    ]
